//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANCH_USER_ROLES
    {
        public string BranchCode { get; set; }
        public string ExistingBranchHead { get; set; }
        public string ExistingBranchAdminUser { get; set; }
        public string NewBranchInCharge { get; set; }
        public string NewBranchHHDAdmin { get; set; }
    }
}
