//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryItem
    {
        public int CategoryItemId { get; set; }
        public int CategoryGroupId { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
    
        public virtual CategoryGroup CategoryGroup { get; set; }
    }
}
