//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_Master
    {
        public string ContractNo { get; set; }
        public string CustomerCode { get; set; }
        public string GuarantorCode { get; set; }
        public string ContractDt { get; set; }
        public string InvoiceDt { get; set; }
        public Nullable<decimal> InvoiceAmt { get; set; }
        public Nullable<decimal> FinAmt { get; set; }
        public Nullable<decimal> FinCharges { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string LastDueDt { get; set; }
        public string Product { get; set; }
        public string Bus_Done_By { get; set; }
        public string Model { get; set; }
        public string Brand { get; set; }
        public string Division { get; set; }
        public string BranchCode { get; set; }
        public string RowFlag { get; set; }
    }
}
