//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_Details
    {
        public string ContractNo { get; set; }
        public string Status { get; set; }
        public string DlCode { get; set; }
        public Nullable<decimal> CurrentMonth { get; set; }
        public Nullable<decimal> Overdue { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> FutureDue { get; set; }
        public Nullable<decimal> SOH { get; set; }
        public string Brachcode { get; set; }
        public string RowFlag { get; set; }
    }
}
