//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.Guarantors = new HashSet<Guarantor>();
            this.ContractCustomInfoes = new HashSet<ContractCustomInfo>();
            this.ContractReceiptMessages = new HashSet<ContractReceiptMessage>();
        }
    
        public int ContractId { get; set; }
        public string ContractNo { get; set; }
        public int BranchId { get; set; }
        public int CustomerId { get; set; }
        public string ContractDt { get; set; }
        public string InvoiceDt { get; set; }
        public Nullable<decimal> InvoiceAmt { get; set; }
        public Nullable<decimal> FinAmt { get; set; }
        public Nullable<decimal> FinCharges { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string LastDueDt { get; set; }
        public string Product { get; set; }
        public string Bus_Done_By { get; set; }
        public string Model { get; set; }
        public string Brand { get; set; }
        public string Division { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guarantor> Guarantors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractCustomInfo> ContractCustomInfoes { get; set; }
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractReceiptMessage> ContractReceiptMessages { get; set; }
    }
}
