//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCustomInfo
    {
        public int CustomerCustomInfoId { get; set; }
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
