//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Master
    {
        public string CustomerCode { get; set; }
        public string Salutation { get; set; }
        public string CustomerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public string PhoneCode { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string PanNo { get; set; }
        public Nullable<int> ContractCount { get; set; }
        public string BranchCode { get; set; }
        public string RowFlag { get; set; }
    }
}
