//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCS_Master
    {
        public string DCS_No { get; set; }
        public string BankCode { get; set; }
        public string Mode { get; set; }
        public string SlipNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public string Gen_Datetime { get; set; }
        public string Tower_Name { get; set; }
    }
}
