//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCSMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DCSMaster()
        {
            this.DCSDCRs = new HashSet<DCSDCR>();
        }
    
        public int DCSMasterId { get; set; }
        public string DCSNumber { get; set; }
        public string BankCode { get; set; }
        public string Mode { get; set; }
        public string SlipNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public string Gen_Datetime { get; set; }
        public string GPSLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DCSDCR> DCSDCRs { get; set; }
    }
}
