//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Master
    {
        public decimal UserID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Company_Division { get; set; }
        public string Product_Division { get; set; }
        public string Status { get; set; }
        public string BranchCode { get; set; }
        public string RowFlag { get; set; }
    }
}
