//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FCMSAPPEntities : DbContext
    {
        public FCMSAPPEntities()
            : base("name=FCMSAPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BRANCH_USER_ROLES> BRANCH_USER_ROLES { get; set; }
        public virtual DbSet<HHT_BLOCKING> HHT_BLOCKING { get; set; }
        public virtual DbSet<HHT_DISPATCH2BRANCH> HHT_DISPATCH2BRANCH { get; set; }
        public virtual DbSet<HHT_INWARD_REGISTER> HHT_INWARD_REGISTER { get; set; }
        public virtual DbSet<HHT_INWARD2BRANCH> HHT_INWARD2BRANCH { get; set; }
        public virtual DbSet<HHT_Master> HHT_Master { get; set; }
        public virtual DbSet<HHT_REASSIGN> HHT_REASSIGN { get; set; }
        public virtual DbSet<HHT_SERVICETRACKER> HHT_SERVICETRACKER { get; set; }
        public virtual DbSet<HTTP_REQUESTS_LOGS> HTTP_REQUESTS_LOGS { get; set; }
        public virtual DbSet<INCREASE_THRESHOLD_LIMIT> INCREASE_THRESHOLD_LIMIT { get; set; }
        public virtual DbSet<PASSWORD_RESET_REQUEST> PASSWORD_RESET_REQUEST { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<Receipts_Cancel> Receipts_Cancel { get; set; }
        public virtual DbSet<Receipts_Denomination> Receipts_Denomination { get; set; }
        public virtual DbSet<Receipts_Deposit_Details> Receipts_Deposit_Details { get; set; }
        public virtual DbSet<Receipts_Details> Receipts_Details { get; set; }
        public virtual DbSet<Receipts_Non_Customers> Receipts_Non_Customers { get; set; }
        public virtual DbSet<Receipts_Representation> Receipts_Representation { get; set; }
        public virtual DbSet<Receipts_Reprint> Receipts_Reprint { get; set; }
        public virtual DbSet<TABLES_USAGE> TABLES_USAGE { get; set; }
        public virtual DbSet<Travel_Debit> Travel_Debit { get; set; }
        public virtual DbSet<USER_BLOCKING> USER_BLOCKING { get; set; }
        public virtual DbSet<User_Master> User_Master { get; set; }
        public virtual DbSet<USER_THRESHOLD_LIMITS> USER_THRESHOLD_LIMITS { get; set; }
        public virtual DbSet<USER_UNBLOCKING> USER_UNBLOCKING { get; set; }
        public virtual DbSet<USER_UNLOCK> USER_UNLOCK { get; set; }
        public virtual DbSet<WEB_USER_ROLES> WEB_USER_ROLES { get; set; }
    }
}
