//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class HHT_Master
    {
        public int MachineID { get; set; }
        public string BranchCode { get; set; }
        public Nullable<System.DateTime> Batch_Date { get; set; }
        public Nullable<System.DateTime> Issued_Date { get; set; }
        public Nullable<System.DateTime> Inward_Date { get; set; }
        public string Serial_No { get; set; }
        public string IMEI_No { get; set; }
        public string Blocked { get; set; }
        public string RowFlag { get; set; }
    }
}
