//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class HHT_SERVICETRACKER
    {
        public string MachineSerialNo { get; set; }
        public string MachineOutwardDate { get; set; }
        public string SentTo { get; set; }
        public string CourierName { get; set; }
        public string PODNo { get; set; }
        public string SentBy { get; set; }
        public string OutwardDate { get; set; }
        public string FaultCategory { get; set; }
        public string DetailsOfCompliant { get; set; }
        public string WhetherAttendedByServieEngineer { get; set; }
        public string ServiceEngineerName { get; set; }
        public string AttendedDate { get; set; }
        public string IntialFeedback { get; set; }
    }
}
