//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class HHT_DISPATCH2BRANCH
    {
        public string MachineSerialNo { get; set; }
        public string MachineOutwardDate { get; set; }
        public string EMIENo { get; set; }
        public string BatteryNo { get; set; }
        public string SIMcardNo { get; set; }
        public string Division { get; set; }
        public string SendTo { get; set; }
        public string CourierName { get; set; }
        public string ConsignmentNumber { get; set; }
    }
}
