//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTTP_REQUESTS_LOGS
    {
        public string URL { get; set; }
        public string REQ_RECVD_DATE { get; set; }
        public string REQ_COMPLETE_DATE { get; set; }
        public string REQ_TYPE { get; set; }
        public string HHT_MECHINEID { get; set; }
        public string HHT_USERNAME { get; set; }
        public string DB_FILE { get; set; }
        public string REQ_RESPONCE { get; set; }
        public string ClientIP { get; set; }
    }
}
