//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCREASE_THRESHOLD_LIMIT
    {
        public string UserEmpNo { get; set; }
        public string EmployeeName { get; set; }
        public string CurrentLimit { get; set; }
        public string LastLimitIncreasedDate { get; set; }
        public string LimitSetBy { get; set; }
        public string IcreaseLimit { get; set; }
        public string LimitSetOn { get; set; }
    }
}
