//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASSWORD_RESET_REQUEST
    {
        public string UserEmpNo { get; set; }
        public string EmployeeName { get; set; }
        public string Status { get; set; }
    }
}
