//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptReprint
    {
        public int ReceiptReprintId { get; set; }
        public int ReceiptId { get; set; }
        public string ReceiptNo { get; set; }
        public string Reprinted_On { get; set; }
        public Nullable<decimal> Reason { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Gen_Datetime { get; set; }
        public string GPSLocation { get; set; }
    
        public virtual Receipt Receipt { get; set; }
    }
}
