//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptCancel
    {
        public int ReceiptNo { get; set; }
        public int ReceiptId { get; set; }
        public string CancelledOn { get; set; }
        public Nullable<decimal> Reason { get; set; }
        public Nullable<decimal> UserID { get; set; }
        public string Gen_Datetime { get; set; }
        public string Tower_Name { get; set; }
        public Nullable<decimal> Auth_UserID { get; set; }
        public string Auth_On { get; set; }
    
        public virtual Receipt Receipt { get; set; }
    }
}
