//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.ReceiptCancels = new HashSet<ReceiptCancel>();
            this.ReceiptsRepresentations = new HashSet<ReceiptsRepresentation>();
            this.ReceiptDetails = new HashSet<ReceiptDetail>();
            this.ReceiptReprints = new HashSet<ReceiptReprint>();
            this.ReceiptDenominations = new HashSet<ReceiptDenomination>();
            this.DCRReceipts = new HashSet<DCRReceipt>();
            this.ReceiptImages = new HashSet<ReceiptImage>();
        }
    
        public int ReceiptId { get; set; }
        public string ReceiptNo { get; set; }
        public string ReceiptDt { get; set; }
        public Nullable<decimal> ReceiptAmt { get; set; }
        public string Mode { get; set; }
        public Nullable<decimal> InstrumentAmt { get; set; }
        public Nullable<decimal> InstrumentNo { get; set; }
        public string InstrumentDt { get; set; }
        public Nullable<decimal> BankID { get; set; }
        public string BranchName { get; set; }
        public Nullable<decimal> MICR { get; set; }
        public string Pay_Clear_location { get; set; }
        public Nullable<decimal> Remitted_By { get; set; }
        public string Remitter_Name { get; set; }
        public Nullable<decimal> Remitter_Relationship { get; set; }
        public string PanNo { get; set; }
        public Nullable<decimal> Rec_Category { get; set; }
        public string BranchCode { get; set; }
        public Nullable<decimal> MachineID { get; set; }
        public string GPSLocation { get; set; }
        public Nullable<int> CollectorUserId { get; set; }
        public Nullable<System.DateTime> Gen_Datetime { get; set; }
        public string CustomerType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptCancel> ReceiptCancels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptsRepresentation> ReceiptsRepresentations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptDetail> ReceiptDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptReprint> ReceiptReprints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptDenomination> ReceiptDenominations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DCRReceipt> DCRReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptImage> ReceiptImages { get; set; }
    }
}
