//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail
    {
        public int ReceiptDetailId { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ContractNo { get; set; }
        public int ReceiptId { get; set; }
    
        public virtual Receipt Receipt { get; set; }
    }
}
