//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptImage
    {
        public int ReceiptImageId { get; set; }
        public int ReceiptId { get; set; }
        public string Description { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageDateTime { get; set; }
    
        public virtual Receipt Receipt { get; set; }
    }
}
