//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelDebitDetail
    {
        public int TravelDebitDetailId { get; set; }
        public int TravelDebitId { get; set; }
        public string ContractNo { get; set; }
    
        public virtual TravelDebit TravelDebit { get; set; }
    }
}
