//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Update
    {
        public int UpdateId { get; set; }
        public int UpdateReasonId { get; set; }
        public string UpdateValue { get; set; }
        public int DeviceId { get; set; }
    
        public virtual UpdateReason UpdateReason { get; set; }
        public virtual Device Device { get; set; }
    }
}
