//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int UserNotificationId { get; set; }
        public int UserId { get; set; }
        public string NoticationType { get; set; }
        public string Message { get; set; }
        public bool IsCommunicated { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTill { get; set; }
    
        public virtual User User { get; set; }
    }
}
