//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_UNBLOCKING
    {
        public string UserEmpNo { get; set; }
        public string EmployeeName { get; set; }
        public string MachineSerialNo { get; set; }
        public string ReasonForBlocking { get; set; }
        public string BlockedBy { get; set; }
        public string BlockedOn { get; set; }
        public string BlockingMode { get; set; }
        public string Status { get; set; }
    }
}
