//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMS.EntityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Master
    {
        public int UserID { get; set; }
        public Nullable<int> Password { get; set; }
        public Nullable<decimal> Threshold_Limit1 { get; set; }
        public Nullable<decimal> Threshold_Limit2 { get; set; }
        public Nullable<decimal> Threshold_Limit3 { get; set; }
        public Nullable<System.DateTime> Last_PWD_Change_Dt { get; set; }
        public Nullable<int> Attempt_Count { get; set; }
        public string Locked { get; set; }
        public string Blocked { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<System.DateTime> Last_Download_Date { get; set; }
        public string RowFlag { get; set; }
    }
}
